title: 'Charles C. Lanfear'
description: "Personal website for Charles C. Lanfear"
logo: 'https://clanfear.github.io/img/circle_headshot_small.png'
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal